# Generated by Django 2.0 on 2018-02-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='salonworker',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.WorkerRole'),
        ),
        migrations.AddField(
            model_name='salonworker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
